name: Simple CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - names: Checkout repository
        uses: actions/Checkout@v3

      - names: Run a simple command
        run: echo "This is my Pipeline run"
